package(default_visibility = ["//source/kdr:__subpackages__"])

filegroup(
    name = "filter_coeff",
    srcs = ["filter_coeff.d"],
)

filegroup(
    name = "ttf",
    srcs = glob(["*.ttf"]),
)

filegroup(
    name = "png",
    srcs = glob(["*.png"]),
)
