name: codecov

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        arch:
          - 'x86_64'
        compiler:
          - 'dmd-beta'
          - 'dmd-latest'
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2

    - name: Install Dependencies - Ubuntu
      if: startsWith(matrix.os,'ubuntu')
      run: |
        sudo apt-get -yq install libx11-dev

    - name: Install compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.compiler }}

    - name: Test synth2
      run: |
        dub test -b=unittest-cov

    - uses: codecov/codecov-action@v2

  Skip:
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04
    steps:
      - name: Skip CI 🚫
        run: echo skip CI
